ayr-ton/awesome-geek-podcasts

.mergify.yml
Implementing this:
https://doc.mergify.io/getting-started.html#configuration
Without CI for the moment.
=> Add Mergify for automerge after reviews

README.md
Pizza de Dados é um dos melhores podcasts sobre ciência de dados em português..
=> Adicionado o podcast Pizza de Dados ao tópico in Portuguese

README.md
#add this lines
* [Land of Giants](https://www.vox.com/land-of-the-giants-podcast) - Facebbok. Apple. Amazon. Netflix. Google. This podcast examine how it got its power, what it's doing with it, and what might happen to in the future.
* [a16z Podcast](https://a16z.com/podcasts/) - A podcast discusses tech and culture trends, news, and the future
=> Adding the Land of giants podcast

README.md
Added Radio Nukular and fixed the alphabetical order in german.
=> Added Radio Nukular and fixed the alphabetical order in german.

.travis.yml, Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ayr-ton/awesome-geek-podcasts/20)
=> Migrate ci steps to Makefile

.github/workflows/awesome-bot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ayr-ton/awesome-geek-podcasts/21)
=> Add GitHub actions

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ayr-ton/awesome-geek-podcasts/22)
=> Add Mamilos podcast

README.md
The podcast is existing for a quite long time and leaders of podcast are doing very good job in discussing IT topics with professionals having deep level of preparation to discussion. Also, they are covering some IT-related topics (like "Health of software engineer", "Mindfullness", "How to write a book", etc.), which are rarely covered by other IT-concentrated podcasts.
=> Add information about Russian podcast Podlodka

README.md
Tales from the Hardware/Software Interface: “the nerdiest podcast on the face of the planet”.
=> Added On the Metal podcast

README.md
=> Add Atareao Podcast

README.md
Added Software sessions Podcast 🔥
=> Added Software sessions Podcast

README.md
Hey @ayr-ton 
the Linux Outlaws podcast seems to have ended.
Cheers,
Peter
=> Remove Linux Outlaws

README.md
update link and description of citizen cosmos
=> Update link and description in the README file

README.md
Adiciona quatro podcasts em português.
=> Adiciona novos podcasts

README.md
added UnderJS Podcast to RU section
=> added UnderJS Podcast

README.md
added new podcast linkmeeup in Russian section
=> added linkmeup podcast

README.md
Added "Laravel Portugal Live" and "Ubuntu Portugal"
=> #hacktoberfest More Portuguese Podcasts

README.md
=> Add podcast in Georgian language

README.md
Updated README.md: 
* Added "Coding Over Cocktails" on English podcasts section
=> Add Coding Over Cocktails podcast

README.md
add Hackers Brasil to portuguese podcasts
=> add Hackers Brasil to portuguese podcasts

README.md
added podtrash (pt) & woff (english) podcasts.
=> added podtrash & woff podcasts

README.md
I am a co-host of AdminAdmin Podcast, and I'm a listener to HPR
=> Added two podcasts

README.md
=> Reverted removing the "ceased production" dates

README.md
Add new podcast of Fernando Herrera, an full stack developer that shares his experience as a developer
=> Add new podcast

README.md
Added two german podcasts:
- Bits und so
- Omega Tau (bilingual)
Added one english podcast:
- Omega Tau (bilingual)
Removed a typo at the methodisch inkorrekt entry
=> Added two german podcasts:

README.md
Add two podcasts In Portuguese, the first about games and the second about tech.
=> Adicionando podcasts em português

README.md
Hi, I've added the software engineering unlocked podcast to the list of English podcasts.
Thanks,
Michaela
=> Add the Software Engineering Unlocked podcast.

README.md
Hello!
I hope you're doing well. I've added some new Portuguese podcasts to the list. These podcasts are a great addition for the community, and I believe they'll resonate with fellow geeks who are looking for awesome content in Portuguese.
I followed the content guidelines provided in the contributing documentation. Each podcast has a short description and is formatted according to the existing entries in the README.
Please review my pull request at your convenience. I'm open to any feedback or suggestions for improvement. Thank you for maintaining this awesome resource, and I'm excited to contribute to it!
Best regards,
Lucca
=> Add new portuguese podcasts

README.md
I don't know French. I just copied the description from the webpage.
=> Add Burger Tech

README.md
I don't know French. I just copied the description from the webpage and replaced the first person pronouns with the podcaster's name.
=> Add S'informer sur la tech

README.md
**It's a Podcast created by Codecon with semanal discussions about the hottest topics of the development's universe.**
Link: [Escovando Bits](https://codecon.dev/podcast)
=> Added the brazilian portugese podcast "Escovando Bits" at README.md

README.md
Ran Segall chats weekly with some of the mentors, students, and friends of Flux Academy. Talking about design, business, life and everything in between.
=> Add Life In Flux

README.md
Pragmatism In Practice is a podcast series for business and technology leaders.
=> Pragmatism In Practice

README.md
Learn from inspiring developers about how they found meaningful and fulfilling work that that also pays them well.
=> Add Scrimba Podcast

README.md
Reverts ayr-ton/awesome-geek-podcasts#108
I didn't see that another CodeNewbie Podcast was already in the list.
=> Revert "Adding the CodeNewbie Podcast."
